name: python39

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip>=20.1
  - conda-forge::gdal>=3.2
  - pip:
    - numpy>=1.2.0
    - tqdm>=4.0.0
    - cdsapi>=0.5.0
    - paramiko>=2.10.0
